### ISSUE TITLE
EOFError when using cPickle.load()

### ISSUE THREAD

**Issue by wangxy524** [DrSleep/tensorflow-deeplab-lfov#20]
When I tried to use the converted model like "model.ckpt-init" or "model.ckpt-pretrained", I met the following error:
Traceback (most recent call last):
    File "/home/wxy/Proj/test.py", line 21, in <module>
        model = DeepLFOV(weights_path)
    ......
    File "/home/wxy/Proj/test.py", line 53, in _create_variable
        weights = cPickle.load(f) # load pre-trained weights
EOFError

**Comment by DrSleep** [comment]
make sure that the file is not corrupted; try to load it in a separate script and check its contents first

**Comment by wangxy524** [comment]
I have tried several times in a separate script using two computer, but I still got the EOFError,
And when I used the "vim" command to edit the file, I see [incomplete last line] [converted]. So I add a line break into the file, it still didn't work.

**Comment by DrSleep** [comment]
Sorry for misleading you - the docs have not been updated in a while: there are two ways of restoring weights, one is via the `weights_path` and another via `restore_from`. The `weights_path` loads the file using the pickle mechanism (after converting the weigths from Caffe), while `restore_from` uses the inner TensorFlow format. Now, the files that are provided are already in the TensorFlow format, so you do not need to pass the `weights_path` variable at all, just `restore_from`.

Let me know if you have any more questions

**Comment by wangxy524** [comment]
I use the **tf.train.Saver().restore** method to retore weights through the converted model "model.ckpt" that you provided, but I get the **DataLossError** which says "Unable to open table file ./model.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?"
